# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master,dev-master ]
  pull_request:
    branches: [ master,dev-master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node-version: [12.x, 13.x, 14.x]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run coverage
    - run: npm run report
    - run: bash <(curl -s https://codecov.io/bash)
